export const ACCOUNT_CODES = {
  CASH_CLEARING: '1000:CASH_CLEARING',
  ORDER_LIABILITY: '2100:ORDER_LIABILITY',
  SALES_REVENUE: '4000:SALES_REVENUE',
  ADJUSTMENTS: '6900:PAYMENT_ADJUSTMENTS',
} as const;
